#!/bin/bash

SCALA_VERSION=2.13.14 ALMOND_VERSION=0.14.0-RC15

# Install coursier
curl -fLo coursier https://github.com/coursier/coursier/raw/gh-pages/coursier
chmod +x coursier

# Install almond
./coursier bootstrap \
    -r jitpack \
    -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
    sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
    --sources --default=true \
    -o almond
./almond --install

# Turn on splitcell
jupyter nbextension enable splitcell/splitcell
